# Generated by Django 3.0 on 2020-02-26 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('city_description', models.TextField()),
                ('city_banner_image', models.TextField()),
                ('city_logo', models.TextField()),
                ('city_thumbnail', models.TextField()),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField()),
                ('city_ranking', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading1', models.TextField()),
                ('heading2', models.TextField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keyword', models.TextField()),
                ('meta_description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=500)),
                ('currency_code', models.CharField(max_length=500)),
                ('banner_image', models.TextField()),
                ('country_logo', models.TextField(max_length=500)),
                ('country_thumbnail', models.TextField()),
                ('description', models.TextField()),
                ('country_ranking', models.PositiveIntegerField()),
                ('isfeatured', models.BooleanField()),
                ('heading1', models.TextField()),
                ('heading2', models.TextField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_keyword', models.TextField()),
                ('meta_description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('banner_image', models.TextField()),
                ('logo', models.TextField()),
                ('thumbnail', models.TextField()),
                ('has_campus', models.CharField(max_length=500)),
                ('campus_detail', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Country')),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Country')),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=500)),
                ('title', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.IntegerField(default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_accomodation.Country'),
        ),
    ]
